import { socket } from "../app";
export const SOCKET_TYPE = {
    SUBMIT_ANSWER: "SUBMIT_ANSWER",
    CHANGE_PRESENTATION: "CHANGE_PRESENTATION",
    NEXT_SLIDE: "NEXT_SLIDE",
    REMOVE_MEMBER: "REMOVE_MEMBER",
    SUBMIT_QUESTION: "SUBMIT_QUESTION",
    UPVOTE_QUESTION: "UPVOTE_QUESTION",
    MARKED_AS_ANWSERED_QUESTION: "MARKED_AS_ANWSERED_QUESTION",
    SEND_MESSAGE: "SEND_MESSAGE",
    START_PRESENTATION: "START_PRESENTATION",
    DELETE_GROUP: "DELETE_GROUP",
};

export const emitMessage = (type, data) => {
    socket.emit(type, data);
};
